services:
  notification-migrate:
    container_name: notification-migrate
    build:
      context: .
      dockerfile: migrate.Dockerfile
    depends_on:
      - postgres
    env_file:
      - app.env
  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - app.env
    ports:
      - 8000:8000
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./db.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
